import { StaffInfoType } from "@/types";

let staff: StaffInfoType[] = [
  {
    id: 1,
    subject: "Математика",
    name: "Име",
    lastname: "Презиме",
    email: "matematika@schools.mk",
  },
  {
    id: 2,
    subject: "Математика",
    name: "Име",
    lastname: "Презиме",
    email: "matematika@schools.mk",
  },
  {
    id: 3,
    subject: "Македонски јазик",
    name: "Име",
    lastname: "Презиме",
    email: "makedonski@schools.mk",
  },
  {
    id: 4,
    subject: "Македонски јазик",
    name: "Име",
    lastname: "Презиме",
    email: "makedonski@schools.mk",
  },
  {
    id: 5,
    subject: "Биологија",
    name: "Име",
    lastname: "Презиме",
    email: "biologija@schools.mk",
  },
  {
    id: 6,
    subject: "Биологија",
    name: "Име",
    lastname: "Презиме",
    email: "biologija@schools.mk",
  },
  {
    id: 7,
    subject: "Биологија",
    name: "Име",
    lastname: "Презиме",
    email: "biologija@schools.mk",
  },
  {
    id: 8,
    subject: "Хемија",
    name: "Име",
    lastname: "Презиме",
    email: "hemija@schools.mk",
  },
  {
    id: 9,
    subject: "Хемија",
    name: "Име",
    lastname: "Презиме",
    email: "hemija@schools.mk",
  },
  {
    id: 10,
    subject: "Хемија",
    name: "Име",
    lastname: "Презиме",
    email: "hemija@schools.mk",
  },
  {
    id: 11,
    subject: "Физика",
    name: "Име",
    lastname: "Презиме",
    email: "fizika@schools.mk",
  },
  {
    id: 12,
    subject: "Физика",
    name: "Име",
    lastname: "Презиме",
    email: "fizika@schools.mk",
  },
  {
    id: 13,
    subject: "Физика",
    name: "Име",
    lastname: "Презиме",
    email: "fizika@schools.mk",
  },
  {
    id: 14,
    subject: "Физика",
    name: "Име",
    lastname: "Презиме",
    email: "fizika@schools.mk",
  },
  {
    id: 15,
    subject: "Физика",
    name: "Име",
    lastname: "Презиме",
    email: "fizika@schools.mk",
  },
  {
    id: 16,
    subject: "Географија",
    name: "Име",
    lastname: "Презиме",
    email: "geografija@schools.mk",
  },
  {
    id: 17,
    subject: "Географија",
    name: "Име",
    lastname: "Презиме",
    email: "geografija@schools.mk",
  },
  {
    id: 18,
    subject: "Англиски јазик",
    name: "Име",
    lastname: "Презиме",
    email: "angliski@schools.mk",
  },
  {
    id: 19,
    subject: "Англиски јазик",
    name: "Име",
    lastname: "Презиме",
    email: "angliski@schools.mk",
  },
  {
    id: 20,
    subject: "Француски јазик",
    name: "Име",
    lastname: "Презиме",
    email: "francuski@schools.mk",
  },
  {
    id: 21,
    subject: "Француски јазик",
    name: "Име",
    lastname: "Презиме",
    email: "francuski@schools.mk",
  },
  {
    id: 22,
    subject: "Германски јазик",
    name: "Име",
    lastname: "Презиме",
    email: "germanski@schools.mk",
  },
  {
    id: 23,
    subject: "Германски јазик",
    name: "Име",
    lastname: "Презиме",
    email: "germanski@schools.mk",
  },
  {
    id: 24,
    subject: "Латински јазик",
    name: "Име",
    lastname: "Презиме",
    email: "latinski@schools.mk",
  },
  {
    id: 25,
    subject: "Информатика",
    name: "Име",
    lastname: "Презиме",
    email: "informatika@schools.mk",
  },
  {
    id: 26,
    subject: "Информатика",
    name: "Име",
    lastname: "Презиме",
    email: "informatika@schools.mk",
  },
  {
    id: 27,
    subject: "Информатика",
    name: "Име",
    lastname: "Презиме",
    email: "informatika@schools.mk",
  },
  {
    id: 28,
    subject: "Информатика",
    name: "Име",
    lastname: "Презиме",
    email: "informatika@schools.mk",
  },
  {
    id: 29,
    subject: "Информатика",
    name: "Име",
    lastname: "Презиме",
    email: "informatika@schools.mk",
  },
  {
    id: 30,
    subject: "Информатика",
    name: "Име",
    lastname: "Презиме",
    email: "informatika@schools.mk",
  },
  {
    id: 31,
    subject: "Историја",
    name: "Име",
    lastname: "Презиме",
    email: "istorija@schools.mk",
  },
  {
    id: 32,
    subject: "Историја",
    name: "Име",
    lastname: "Презиме",
    email: "istorija@schools.mk",
  },
  {
    id: 33,
    subject: "Историја",
    name: "Име",
    lastname: "Презиме",
    email: "istorija@schools.mk",
  },
  {
    id: 34,
    subject: "Социологија",
    name: "Име",
    lastname: "Презиме",
    email: "sociologija@schools.mk",
  },
  {
    id: 35,
    subject: "Социологија",
    name: "Име",
    lastname: "Презиме",
    email: "sociologija@schools.mk",
  },
  {
    id: 36,
    subject: "Ликовна уметност",
    name: "Име",
    lastname: "Презиме",
    email: "likovna@schools.mk",
  },
  {
    id: 37,
    subject: "Ликовна уметност",
    name: "Име",
    lastname: "Презиме",
    email: "likovna@schools.mk",
  },
  {
    id: 38,
    subject: "Музичка уметност",
    name: "Име",
    lastname: "Презиме",
    email: "muzicka@schools.mk",
  },
  {
    id: 39,
    subject: "Музичка уметност",
    name: "Име",
    lastname: "Презиме",
    email: "muzicka@schools.mk",
  },
  {
    id: 40,
    subject: "Музичка уметност",
    name: "Име",
    lastname: "Презиме",
    email: "muzicka@schools.mk",
  },
  {
    id: 41,
    subject: "Спорт и спортски активности",
    name: "Име",
    lastname: "Презиме",
    email: "sport@schools.mk",
  },
  {
    id: 42,
    subject: "Спорт и спортски активности",
    name: "Име",
    lastname: "Презиме",
    email: "sport@schools.mk",
  },
  {
    id: 43,
    subject: "Бизнис, менаџмент и економија",
    name: "Име",
    lastname: "Презиме",
    email: "biznis@schools.mk",
  },
  {
    id: 44,
    subject: "Бизнис, менаџмент и економија",
    name: "Име",
    lastname: "Презиме",
    email: "biznis@schools.mk",
  },
  {
    id: 45,
    subject: "Бизнис, менаџмент и економија",
    name: "Име",
    lastname: "Презиме",
    email: "biznis@schools.mk",
  },
  {
    id: 46,
    subject: "Филозофија, логика и етика",
    name: "Име",
    lastname: "Презиме",
    email: "filozofija@schools.mk",
  },
  {
    id: 47,
    subject: "Филозофија, логика и етика",
    name: "Име",
    lastname: "Презиме",
    email: "filozofija@schools.mk",
  },
  {
    id: 48,
    subject: "Филозофија, логика и етика",
    name: "Име",
    lastname: "Презиме",
    email: "filozofija@schools.mk",
  },
  {
    id: 49,
    subject: "Вовед во право",
    name: "Име",
    lastname: "Презиме",
    email: "pravo@schools.mk",
  },
  {
    id: 50,
    subject: "Вовед во право",
    name: "Име",
    lastname: "Презиме",
    email: "pravo@schools.mk",
  },
  {
    id: 51,
    subject: "Психологија",
    name: "Име",
    lastname: "Презиме",
    email: "psihologija@schools.mk",
  },
  {
    id: 52,
    subject: "Педагогија",
    name: "Име",
    lastname: "Презиме",
    email: "pedagogija@schools.mk",
  },
  {
    id: 53,
    subject: "Раководител на смена",
    name: "Име",
    lastname: "Презиме",
    email: "rakovoditel@schools.mk",
  },
  {
    id: 54,
    subject: "Раководител на смена",
    name: "Име",
    lastname: "Презиме",
    email: "rakovoditel@schools.mk",
  },
];

export default staff;
